import { LayoutDefault } from "@/components/_Layout-Default"

import {Inter, PT_Sans_Caption} from "next/font/google"

import "@/styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({
  subsets: ['latin'],
  style: ['normal', 'italic'],
  weight: ['400', '500']
})

const ptSansCaption = PT_Sans_Caption({
  subsets: ['latin'],
  style: 'normal',
  weight: ['700']
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <LayoutDefault className={`${inter.className} ${ptSansCaption.className}`}>
          {children}
        </LayoutDefault>
      </body>
    </html>
  )
}
